### ISSUE TITLE
disable XHCIportlimit

### ISSUE THREAD

**Issue by FarisZR** [ARhackintosh/OC-Configs#10]
XHCIportlimit no longer works in macOS 11.3 and actively causes problems

https://github.com/ARhackintosh/ARtutorial/issues/10

https://github.com/dortania/OpenCore-Install-Guide/pull/238

https://github.com/acidanthera/bugtracker/issues/1514

**Comment by ahmedn6600** [comment]
fixd by Disabled XHCIPortlimit
